In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,3])


In [6]:
matrix = tf.constant([[10,3],
                      [5,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 5,  5]])>

In [7]:
matrix.ndim

2

In [8]:
dif_matrix = tf.constant([[10.,3.],
                          [5.,5.],
                          [3.,13.]], dtype= tf.float16)
dif_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 5.,  5.],
       [ 3., 13.]], dtype=float16)>

In [9]:
tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])>

In [10]:
tf_var = tf.Variable([3,4])
tf_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>