In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,3])


In [6]:
matrix = tf.constant([[10,3],
                      [5,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 5,  5]])>

In [7]:
matrix.ndim

2

In [8]:
dif_matrix = tf.constant([[10.,3.],
                          [5.,5.],
                          [3.,13.]], dtype= tf.float16)
dif_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 5.,  5.],
       [ 3., 13.]], dtype=float16)>

In [9]:
tensor = tf.constant([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])>

In [15]:
tf_var = tf.Variable([3,4])
tf_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>

In [18]:
tf_var[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 4])>

In [24]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = [3,2])
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [34]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [37]:
tf.ones((3,2)), tf.zeros((2,3))

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [50]:
r1 = tf.random.uniform(shape = (3,2))
r2 = tf.random.uniform(shape = (2,6))
r1 @ r2

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0.82426304, 0.75098807, 0.17623785, 0.4093716 , 0.19977093,
        0.10087184],
       [0.6624899 , 0.6129126 , 0.2096304 , 0.27695048, 0.27027518,
        0.12910375],
       [0.4014611 , 0.38461864, 0.22335987, 0.09403946, 0.31923965,
        0.1462904 ]], dtype=float32)>